input {
  file {
    path => "C:/Users/lenovo/OneDrive/Desktop/GRAD PROJECT/simulated_stream.jsonl"
    start_position => "beginning"
    sincedb_path => "NUL"
    stat_interval => 1
    codec => json
  }
}

filter {
  mutate {
    remove_field => ["@version", "@timestamp", "host", "path"]
  }
}

output {
  http {
    url => "http://127.0.0.1:5000/analyze_log"
    http_method => "post"
    format => "json"
  }

  stdout { codec => rubydebug }
}
